-- Справочник MPA‑рейтингов
CREATE TABLE IF NOT EXISTS mpa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    release_date DATE    NOT NULL,
    duration     INT     NOT NULL,
    mpa_id   VARCHAR(10),
    FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id         INT AUTO_INCREMENT  PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    login      VARCHAR(100) NOT NULL,
    name       VARCHAR(150),
    birthday   DATE
);

-- Таблица лайков фильмов
CREATE TABLE IF NOT EXISTS film_likes (
    film_id INT NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Справочник статусов дружбы
CREATE TABLE IF NOT EXISTS friendship_statuses (
    code        VARCHAR(50) PRIMARY KEY,
    description VARCHAR(255)
);

-- Связь «пользователь → пользователь» с указанием статуса
CREATE TABLE IF NOT EXISTS user_friends (
    requester_id INT       NOT NULL,
    addressee_id INT       NOT NULL,
    status_code  VARCHAR(50) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (requester_id, addressee_id),
    FOREIGN KEY (requester_id)   REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (addressee_id)   REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (status_code)    REFERENCES friendship_statuses(code)
);

-- Справочник жанров
CREATE TABLE IF NOT EXISTS genres (
    id   INT          PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- Связь «фильм ↔ жанр»
CREATE TABLE IF NOT EXISTS film_genres (
    film_id  INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id)  REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    is_positive BOOLEAN NOT NULL DEFAULT TRUE,
    user_id INT NOT NULL,
    film_id INT NOT NULL,
    useful INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id INT NOT NULL,
    user_id INT NOT NULL,
    is_useful BOOLEAN NOT NULL,
    CONSTRAINT pk_review_likes PRIMARY KEY (review_id, user_id),
    CONSTRAINT fk_review_likes_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_likes_user FOREIGN KEY (user_id)   REFERENCES users(id) ON DELETE CASCADE
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_films_name ON films(name);
CREATE INDEX IF NOT EXISTS idx_genres_name ON genres(name);

-- Создание таблицы режиссеров
CREATE TABLE IF NOT EXISTS directors (
    director_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

-- Создание таблицы связи фильмов и режиссеров
CREATE TABLE IF NOT EXISTS film_directors (
    film_id INTEGER NOT NULL,
    director_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors(director_id) ON DELETE CASCADE
);

-- Создание таблицы ленты событий
create table if not exists feeds
(
    eventId   int generated by default as identity primary key,
    userId    int NOT NULL,
    timestamp long,
    eventType varchar(10),
    operation varchar(10),
    entityId  BIGINT NOT NULL
);